"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import LanguageManager from "./language-manager";

type Row=Record<string,string|number|null>;
type Data={applications:Row[];partners:Row[];payments:Row[];documents:Row[];refreshedAt:string};
type DataSection="applications"|"partners"|"payments";
type Section=DataSection|"languages";
const statusOptions:Record<DataSection,string[]>={applications:["submitted","reviewing","documents-needed","approved","rejected","supported"],partners:["new","contacted","meeting","committed","closed"],payments:["created","paid","failed","refunded"]};

export default function AdminDashboard({adminName}:{adminName:string}){
 const [data,setData]=useState<Data|null>(null),[section,setSection]=useState<Section>("applications"),[query,setQuery]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[updating,setUpdating]=useState<number|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/admin/data",{cache:"no-store"});const body=await response.json();if(response.ok)setData(body);else setError(body.error||"Unable to load dashboard.")}catch{setError("Unable to connect to the admin database.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const rows=useMemo(()=>{if(section==="languages")return [];const items=data?.[section]||[];const needle=query.trim().toLowerCase();return needle?items.filter(row=>Object.values(row).some(value=>String(value??"").toLowerCase().includes(needle))):items},[data,section,query]);
 const paid=(data?.payments||[]).filter(x=>x.status==="paid"),total=paid.reduce((sum,row)=>sum+Number(row.amount||0),0)/100,pendingDocs=(data?.documents||[]).reduce((sum,row)=>sum+Number(row.pending||0),0);
 async function updateStatus(id:number,status:string){if(section==="languages")return;setUpdating(id);const response=await fetch("/api/admin/data",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({section,id,status})});if(response.ok)await load();else setError("Status update failed.");setUpdating(null)}
 return <><div className="admin-heading"><div><p className="eyebrow">Live operations</p><h1>Admin Control Centre</h1><p>Welcome, {adminName}. Manage operations and website languages from one place.</p></div><div className="admin-heading-actions"><button className="btn btn-outline" onClick={()=>void load()} disabled={loading}><i className={`fa-solid fa-rotate ${loading?"fa-spin":""}`}/> Refresh</button><a href="/api/admin/logout" className="btn btn-outline"><i className="fa-solid fa-right-from-bracket"/> Sign out</a></div></div><div className="admin-kpis"><article><i className="fa-solid fa-folder-open"/><b>{data?.applications.length??"—"}</b><span>Total applications</span></article><article><i className="fa-solid fa-file-circle-exclamation"/><b>{data?pendingDocs:"—"}</b><span>Pending documents</span></article><article><i className="fa-solid fa-indian-rupee-sign"/><b>{data?`₹${total.toLocaleString("en-IN")}`:"—"}</b><span>Verified donations</span></article><article><i className="fa-solid fa-handshake"/><b>{data?.partners.filter(x=>x.status!=="closed").length??"—"}</b><span>Open partner leads</span></article></div><section className="admin-workspace"><div className="admin-toolbar"><div className="admin-tabs">{(["applications","partners","payments","languages"] as Section[]).map(item=><button key={item} className={section===item?"active":""} onClick={()=>{setSection(item);setQuery("")}}>{item}</button>)}</div>{section!=="languages"&&<label className="admin-search"><i className="fa-solid fa-magnifying-glass"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${section}`}/></label>}</div>{section==="languages"?<LanguageManager/>:<>{error&&<div className="admin-error"><i className="fa-solid fa-triangle-exclamation"/> {error}</div>}{loading&&!data?<div className="admin-empty"><i className="fa-solid fa-spinner fa-spin"/> Initialising secure admin data…</div>:<AdminTable section={section} rows={rows} updating={updating} updateStatus={updateStatus}/>}<p className="admin-refreshed">{data?.refreshedAt&&`Last refreshed ${new Date(data.refreshedAt).toLocaleString("en-IN")}`}</p></>}</section></>
}

function AdminTable({section,rows,updating,updateStatus}:{section:DataSection;rows:Row[];updating:number|null;updateStatus:(id:number,status:string)=>void}){if(!rows.length)return <div className="admin-empty"><i className="fa-solid fa-inbox"/><b>No records found</b><span>New records will appear here automatically.</span></div>;return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{section==="applications"?<><th>Reference / Applicant</th><th>Support</th><th>Contact</th><th>Documents</th><th>Status</th></>:section==="partners"?<><th>Organisation</th><th>Contact</th><th>Message</th><th>Status</th></>:<><th>Razorpay order</th><th>Amount</th><th>Created</th><th>Status</th></>}</tr></thead><tbody>{rows.map(row=><tr key={Number(row.id)}>{section==="applications"?<><td><b>{row.reference}</b><span>{row.name} · {row.district}</span></td><td>{row.category}<span>{row.details}</span></td><td>{row.phone}</td><td><span className="status-chip">Stored securely</span></td></>:section==="partners"?<><td><b>{row.company}</b></td><td>{row.contact_name}<span>{row.email}</span></td><td>{row.message}</td></>:<><td><b>{row.razorpay_order_id}</b></td><td>₹{(Number(row.amount)/100).toLocaleString("en-IN")}</td><td>{String(row.created_at||"")}</td></>}<td><select value={String(row.status)} disabled={updating===row.id} onChange={e=>updateStatus(Number(row.id),e.target.value)}>{statusOptions[section].map(status=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div>}
