/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { confirmDelete, popupError, popupSuccess } from "../sweet-alert";

type Language={id:number;locale:string;name:string;native_name:string;enabled:number;sort_order:number;created_at:string};
type Count={locale:string;translation_count:number};

export default function LanguageManager(){
 const [languages,setLanguages]=useState<Language[]>([]),[counts,setCounts]=useState<Record<string,number>>({}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");const response=await fetch("/api/admin/languages",{cache:"no-store"});const body=await response.json();if(response.ok){setLanguages(body.languages);setCounts(Object.fromEntries((body.counts as Count[]).map(x=>[x.locale,Number(x.translation_count)])))}else setError(body.error||"Unable to load languages.");setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));const response=await fetch("/api/admin/languages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale:values.locale,name:values.name,nativeName:values.nativeName})});const body=await response.json();if(response.ok){form.reset();await load();await popupSuccess("Language added",`${values.name} is now available.`)}else{setError(body.error);await popupError("Could not add language",body.error)}}
 async function toggle(item:Language){const response=await fetch("/api/admin/languages",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({locale:item.locale,enabled:!item.enabled})});if(response.ok){await load();await popupSuccess(item.enabled?"Language hidden":"Language enabled",`${item.name} was updated.`)}else{const message=(await response.json()).error;setError(message);await popupError("Update failed",message)}}
 async function remove(item:Language){const confirmation=await confirmDelete(`Delete ${item.name}?`,"The language and all saved translations will be permanently removed.");if(!confirmation.isConfirmed)return;const response=await fetch(`/api/admin/languages?locale=${encodeURIComponent(item.locale)}`,{method:"DELETE"});if(response.ok){await load();await popupSuccess("Language deleted",`${item.name} was removed.`)}else{const message=(await response.json()).error;setError(message);await popupError("Delete failed",message)}}
 return <div className="language-manager">{error&&<div className="admin-error"><i className="fa-solid fa-triangle-exclamation"/> {error}</div>}<form className="language-add" onSubmit={add}><div><h2>Add language</h2><p>Add a locale to the public website language selector.</p></div><label>Locale code<input name="locale" required placeholder="e.g. gu or en-US" pattern="[a-z]{2,3}(-[A-Z]{2})?"/></label><label>English name<input name="name" required placeholder="Gujarati"/></label><label>Native name<input name="nativeName" required placeholder="ગુજરાતી"/></label><button className="btn btn-gold" type="submit"><i className="fa-solid fa-plus"/> Add language</button></form>{loading?<div className="admin-empty"><i className="fa-solid fa-spinner fa-spin"/> Loading languages…</div>:<div className="language-list">{languages.map(item=><article key={item.locale} className={item.enabled?"":"disabled"}><div className="language-symbol">{item.locale.toUpperCase()}</div><div><h3>{item.native_name}</h3><p>{item.name} · {counts[item.locale]||0} custom translations</p></div><span className={`status-chip ${item.enabled?"enabled":""}`}>{item.enabled?"Visible":"Hidden"}</span><button className="language-toggle" onClick={()=>void toggle(item)} disabled={item.locale==="en"} aria-label={`${item.enabled?"Hide":"Show"} ${item.name}`}><i className={`fa-solid ${item.enabled?"fa-toggle-on":"fa-toggle-off"}`}/></button><button className="language-delete" onClick={()=>void remove(item)} disabled={item.locale==="en"} aria-label={`Delete ${item.name}`}><i className="fa-solid fa-trash"/></button></article>)}</div>}</div>
}
