from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

OUT="output/pdf/beyond-disability-csr-brochure.pdf"; NAVY=colors.HexColor("#062F63"); GOLD=colors.HexColor("#FFBD18")
s=getSampleStyleSheet(); s.add(ParagraphStyle(name="Gold",parent=s["Heading2"],textColor=GOLD,fontSize=17,leading=21,spaceAfter=8)); s.add(ParagraphStyle(name="BodyNavy",parent=s["BodyText"],textColor=NAVY,fontSize=10.5,leading=16)); s.add(ParagraphStyle(name="CellHead",parent=s["BodyText"],textColor=NAVY,fontName="Helvetica-Bold",fontSize=9,leading=11)); s.add(ParagraphStyle(name="CellBody",parent=s["BodyText"],textColor=NAVY,fontSize=8.5,leading=11))
def p(txt,style="BodyNavy"): return Paragraph(txt,s[style])
def table(head,body):
 return Table([[p(x,"CellHead") for x in head],[p(x,"CellBody") for x in body]],colWidths=[58*mm]*3,style=TableStyle([("BACKGROUND",(0,0),(-1,0),GOLD),("BOX",(0,0),(-1,-1),.6,NAVY),("INNERGRID",(0,0),(-1,-1),.3,NAVY),("VALIGN",(0,0),(-1,-1),"TOP"),("PADDING",(0,0),(-1,-1),8)]))
def hf(c,d):
 c.saveState(); c.setFillColor(NAVY); c.rect(0,A4[1]-17*mm,A4[0],17*mm,fill=1,stroke=0); c.setFillColor(colors.white); c.setFont("Helvetica-Bold",10); c.drawString(18*mm,A4[1]-11*mm,"BEYOND DISABILITY FOUNDATION"); c.setFillColor(NAVY); c.setFont("Helvetica",8); c.drawString(18*mm,11*mm,"csr@beyonddisability.org  |  +91 80000 12345"); c.drawRightString(A4[0]-18*mm,11*mm,f"Page {d.page}"); c.restoreState()
doc=SimpleDocTemplate(OUT,pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=25*mm,bottomMargin=20*mm)
title=Table([[Paragraph("Partner in Our Growth",ParagraphStyle(name="T",parent=s["Title"],textColor=colors.white,fontSize=30,leading=34,alignment=TA_CENTER))],[Paragraph("Join hands. Change lives across Uttar Pradesh.",ParagraphStyle(name="Sub",parent=s["BodyText"],textColor=colors.white,alignment=TA_CENTER,fontSize=13))]],colWidths=[174*mm],rowHeights=[28*mm,18*mm],style=TableStyle([("BACKGROUND",(0,0),(-1,-1),NAVY),("VALIGN",(0,0),(-1,-1),"MIDDLE")]))
story=[Spacer(1,28*mm),title,Spacer(1,12*mm),p("A Specialized Model. A Replicable Impact.","Gold"),p("Beyond Disability Foundation provides direct financial and practical support for assistive technology, cochlear implant maintenance and specialized therapy. We are expanding from major cities to every district of Uttar Pradesh, with a future pan-India support network."),Spacer(1,8*mm),p("Where CSR Support Creates Impact","Gold"),table(["Cochlear Life-Support","Digital Empowerment","Therapeutic Aid"],["Cables, batteries and coils that keep the gift of hearing active.","Smartphones and laptops that unlock accessible education.","Financial grants for Autism, Speech and OT interventions."]),PageBreak(),p("Partnership Opportunities","Gold"),p("Sponsor assistive devices, fund therapies, support lifetime maintenance, build digital classrooms or collaborate on awareness campaigns. Partnerships can be designed around district, service category, beneficiary cohort or an annual impact goal."),Spacer(1,8*mm),p("What Partners Receive","Gold"),p("- Transparent utilization and impact reports<br/>- Brand visibility aligned with programme delivery<br/>- Field-visit and beneficiary engagement opportunities<br/>- CSR compliance documentation support<br/>- A long-term, measurable partnership roadmap"),Spacer(1,8*mm),p("Our Growth Roadmap","Gold"),table(["Phase 1 - Achieved","Phase 2 - Current","Phase 3 - Future"],["500+ lives supported in major cities.","Reaching all 75 districts of Uttar Pradesh.","A pan-India network for CI maintenance and assistive technology."]),Spacer(1,14*mm),Table([[p("Start a CSR Conversation","Gold")],[Paragraph("csr@beyonddisability.org  |  +91 80000 12345  |  Kanpur, Uttar Pradesh",ParagraphStyle(name="C",parent=s["BodyText"],textColor=NAVY,alignment=TA_CENTER))]],colWidths=[174*mm],style=TableStyle([("BACKGROUND",(0,0),(-1,-1),GOLD),("ALIGN",(0,0),(-1,-1),"CENTER"),("PADDING",(0,0),(-1,-1),10)]))]
doc.build(story,onFirstPage=hf,onLaterPages=hf)
