"use client";
import { useState } from "react";
import { PageShell } from "../components";
declare global { interface Window { Razorpay?: new (options:Record<string,unknown>)=>{open:()=>void} } }
export default function Donate(){
 const [amount,setAmount]=useState(1000),[frequency,setFrequency]=useState<'one-time'|'monthly'>('one-time'),[method,setMethod]=useState('upi'),[status,setStatus]=useState('');
 function loadCheckout(){return new Promise<boolean>((resolve)=>{if(window.Razorpay)return resolve(true);const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
 async function pay(){setStatus('Preparing secure payment…');if(!amount||amount<100){setStatus('Please choose an amount of at least ₹100.');return}const res=await fetch('/api/payments/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount,frequency,method})});const data=await res.json() as Record<string,string>;if(!res.ok||!data.id){setStatus(data.message||data.error||'Payment service is not configured yet.');return}if(!(await loadCheckout())||!window.Razorpay){setStatus('Secure checkout could not load. Please check your connection.');return}const checkout=new window.Razorpay({key:data.key,amount:data.amount,currency:'INR',name:'Beyond Disability Foundation',description:`${frequency==='monthly'?'Monthly':'One-time'} contribution`,order_id:data.id,method:{[method]:true},handler:async(response:Record<string,string>)=>{const verify=await fetch('/api/payments/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(response)});setStatus(verify.ok?'Thank you. Your payment was verified and your receipt is being prepared.':'Payment received; verification is pending. Please contact support with your payment ID.')},modal:{ondismiss:()=>setStatus('Payment window closed. No charge was made.')},theme:{color:'#ffbd18'}});checkout.open();setStatus('Secure checkout opened.')}
 return <PageShell><section className="donate"><h1>Support Our Mission</h1><b>Every contribution creates a life-changing impact.</b><p>Choose a convenient way to contribute.</p><div className="donate-box"><div className="tabs"><button className={frequency==='one-time'?'selected-tab':''} onClick={()=>setFrequency('one-time')}>One-time Donation</button><button className={frequency==='monthly'?'selected-tab':''} onClick={()=>setFrequency('monthly')}>Monthly Donation</button></div><div className="amounts">{[500,1000,2500,5000].map(n=><button className={amount===n?'selected':''} onClick={()=>setAmount(n)} key={n}>₹{n.toLocaleString('en-IN')}</button>)}<input aria-label="Custom amount" type="number" min="100" placeholder="Custom" onChange={e=>setAmount(Number(e.target.value))}/></div><h2>Payment Options</h2><div className="payment-grid"><div className="payment-methods">{[['upi','UPI','UPI'],['card','Card','VISA · RuPay'],['netbanking','Net Banking','Banks'],['wallet','Wallets','Paytm · GPay']].map(([id,label,brands])=><button key={id} className={method===id?'chosen':''} onClick={()=>setMethod(id)}><span>{label}</span><b>{brands} →</b></button>)}</div><aside><div className="qr">▦</div><b>Scan & Pay</b><small>UPI ID: beyonddisability@upi</small></aside></div><button className="btn btn-gold pay" onClick={pay}>Donate Now Securely 🔒</button><p className="center form-status" role="status">{status}</p></div><div className="trust"><span>80G Tax Exemption</span><span>Transparent & Verified</span><span>Secure Payments</span><span>100% Impact Driven</span></div></section></PageShell>}
