"use client";
import { useState } from "react";
import { PageShell } from "../components";
declare global { interface Window { Razorpay?: new (options:Record<string,unknown>)=>{open:()=>void} } }
export default function Donate(){
 const [amount,setAmount]=useState(1000),[frequency,setFrequency]=useState<'one-time'|'monthly'>('one-time'),[method,setMethod]=useState('upi'),[status,setStatus]=useState('');
 function loadCheckout(){return new Promise<boolean>((resolve)=>{if(window.Razorpay)return resolve(true);const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
 async function pay(selectedMethod=method){setMethod(selectedMethod);setStatus('Preparing secure payment…');if(!amount||amount<1){setStatus('Please choose an amount of at least ₹1.');return}const res=await fetch('/api/payments/order',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount,frequency,method:selectedMethod})});const data=await res.json() as Record<string,string>;if(!res.ok||!data.id){setStatus(data.message||data.error||'Payment service is not configured yet.');return}if(!(await loadCheckout())||!window.Razorpay){setStatus('Secure checkout could not load. Please check your connection.');return}const checkout=new window.Razorpay({key:data.key,amount:data.amount,currency:'INR',description:`${frequency==='monthly'?'Monthly':'One-time'} contribution`,order_id:data.id,config:{display:{blocks:{preferred:{name:`Pay via ${selectedMethod==='netbanking'?'Net Banking':selectedMethod.toUpperCase()}`,instruments:[{method:selectedMethod}]}},sequence:['block.preferred'],preferences:{show_default_blocks:true}}},handler:async(response:Record<string,string>)=>{const verify=await fetch('/api/payments/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(response)});setStatus(verify.ok?'Thank you. Your payment was verified and your receipt is being prepared.':'Payment received; verification is pending. Please contact support with your payment ID.')},modal:{ondismiss:()=>setStatus('Payment window closed. No charge was made.')},theme:{color:'#ffbd18'}});checkout.open();setStatus('Secure Razorpay checkout opened.')}
 return <PageShell><section className="donate"><h1><i className="fa-solid fa-heart"/> Support Our Mission</h1><b>Every contribution creates a life-changing impact.</b><p>Choose a convenient way to contribute.</p><div className="donate-box"><div className="tabs"><button className={frequency==='one-time'?'selected-tab':''} onClick={()=>setFrequency('one-time')}><i className="fa-solid fa-hand-holding-heart"/> One-time Donation</button><button className={frequency==='monthly'?'selected-tab':''} onClick={()=>setFrequency('monthly')}><i className="fa-solid fa-calendar-check"/> Monthly Donation</button></div><div className="amounts">{[500,1000,2500,5000].map(n=><button className={amount===n?'selected':''} onClick={()=>setAmount(n)} key={n}>₹{n.toLocaleString('en-IN')}</button>)}<input aria-label="Custom amount" type="number" min="1" placeholder="Custom" onChange={e=>setAmount(Number(e.target.value))}/></div><h2><i className="fa-solid fa-credit-card"/> Payment Options</h2><div className="payment-grid"><div className="payment-methods">{[['upi','UPI','UPI'],['card','Card','VISA · RuPay'],['netbanking','Net Banking','Banks'],['wallet','Wallets','Paytm · GPay']].map(([id,label,brands])=><button key={id} className={method===id?'chosen':''} onClick={()=>pay(id)}><span>{label}</span><b>{brands} <i className="fa-solid fa-arrow-right"/></b></button>)}</div><aside><button className="qr-launch" type="button" onClick={()=>pay('upi')} aria-label="Open Razorpay UPI QR payment"><div className="qr"><i className="fa-solid fa-qrcode"/></div><b>Scan & Pay</b><small>Generate secure QR with Razorpay</small></button></aside></div><button className="btn btn-gold pay" onClick={()=>pay(method)}><i className="fa-solid fa-lock"/> Pay with Razorpay</button><p className="center form-status" role="status">{status}</p></div><div className="trust"><span><i className="fa-solid fa-receipt"/>80G Tax Exemption</span><span><i className="fa-solid fa-circle-check"/>Transparent & Verified</span><span><i className="fa-solid fa-shield-halved"/>Secure Payments</span><span><i className="fa-solid fa-bullseye"/>100% Impact Driven</span></div></section></PageShell>}
